### ISSUE TITLE
Peer to Peer

### ISSUE THREAD

**Issue by Debas-31** [thecodechaser/todo-list#3]

**Comment by arnrdn** [comment]
Hello, Ranjeet! 

Your code is awesome and I don't have any suggestions! You did a really great job here!

Kindly,
Nana

**Comment by thecodechaser** [comment]
> Hello, Ranjeet!
> 
> Your code is awesome and I don't have any suggestions! You did a really great job here!
> 
> Kindly, Nana

Hello @rdnrn 

Thank you for your feedback, It will help me to stay motivated.

**Comment by Debas-31** [comment]
God Job @thecodechaser 💯 
-  on UI

**Comment by Debas-31** [comment]
Great Job @thecodechaser 💯 
Nothing to say your code is so clean.

**Comment by thecodechaser** [comment]
> God Job @thecodechaser 💯
> 
> * on UI

Hello @Debas-31 👋 

Thank you for your feedback.

**Comment by patriciachrysy** [comment]
Great job on your code, i really appreciated the way you organised your code!!! It's so clean and pleasant to read!!!
I just have few suggestions:
- The UI need some improvement to look as the original on(align elements, give some colors, add some padding, hover and focus styles and also you are missing some icons on the task list)
- Most of your code is in Javascript, not ES6, maybe you should consider using arrow functions more often
- Try to put as less code in the HTML by creating your elements in the js files and keep only the main container div in the HTML

**Comment by thecodechaser** [comment]
> Great job on your code, i really appreciated the way you organised your code!!! It's so clean and pleasant to read!!! I just have few suggestions:
> 
> * The UI need some improvement to look as the original on(align elements, give some colors, add some padding, hover and focus styles and also you are missing some icons on the task list)
> * Most of your code is in Javascript, not ES6, maybe you should consider using arrow functions more often
> * Try to put as less code in the HTML by creating your elements in the js files and keep only the main container div in the HTML

Helllo @patriciachrysy 👋 

Thank you for your feedback and suggestions, I will work on the changes you suggested.
